# Generated by Django 3.0.2 on 2020-05-31 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=300)),
                ('brand_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('descript', models.TextField(default='Enter', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_title', models.CharField(max_length=300)),
                ('prod_model', models.CharField(max_length=300)),
                ('rating', models.FloatField()),
                ('descr', models.TextField(default='give', max_length=1000)),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='main_product')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_end.Brand')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_end.Categories')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_end.Categories'),
        ),
    ]
