# Generated by Django 3.0.2 on 2020-05-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_end', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='description',
        ),
        migrations.AddField(
            model_name='categories',
            name='descript',
            field=models.TextField(default='Enter', max_length=1000),
        ),
    ]
