# Generated by Django 3.0.2 on 2020-05-30 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_end', '0002_auto_20200530_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=300)),
                ('brand_description', models.TextField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_end.Categories')),
            ],
        ),
    ]
