# Generated by Django 3.0.2 on 2020-05-30 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_end', '0003_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand_description',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='descript',
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_title', models.CharField(max_length=300)),
                ('prod_model', models.CharField(max_length=300)),
                ('rating', models.FloatField()),
                ('descr', models.TextField(default='give', max_length=1000)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_end.Brand')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_end.Categories')),
            ],
        ),
    ]
